### ISSUE TITLE
テスト Issue

### ISSUE THREAD

**Issue by kjirou** [kjirou/github-playground#8]
Hello!

**Comment by kjirou** [comment]
```js
class Unit {
  render() {
    return (
      <div className="unit">(
          <div className="goblin-icon" />
          <div className="hp">{ this.props.hp }</div>
      </div>
    );
  }
}
```

**Comment by kjirou** [comment]
```js
import React from 'react';

class Unit extends React.Component {
  render() {
    return (
      <div className="unit">
          <div className={ this.props.effect} />
          <div className={ this.props.icon } />
          <div className="hp">{ this.props.hp }</div>
      </div>
    );
  }
}

Object.assign(Unit, {
  propTypes: {
    effect: React.PropTypes.string,
    icon: React.PropTypes.string.isRequired,
    hp: React.PropTypes.number.isRequired,
  },
});
```

**Comment by kjirou** [comment]
```js
import React from 'react';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';

class Unit extends React.Component {
  render() {
    let effect = null;
    if (this.props.effect) {
      effect = <div className={ this.props.effect} />;
    }
    return (
      <div className="unit">
        <ReactCSSTransitionGroup
          transitionName="showing"
          transitionEnterTimeout={ 250 }
          transitionLeaveTimeout={ 250 }
        >
          { effect }
        </ReactCSSTransitionGroup>
        <div className={ this.props.icon } />
        <div className="hp">{ this.props.hp }</div>
      </div>
    );
  }
}

Object.assign(Unit, {
  propTypes: {
    effect: React.PropTypes.string,
    icon: React.PropTypes.string.isRequired,
    hp: React.PropTypes.number.isRequired,
  },
});
```

**Comment by kjirou** [comment]
```js
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';

<ReactCSSTransitionGroup
  transitionName="example"
  transitionEnterTimeout={500}
  transitionLeaveTimeout={300}
>
  {items}
</ReactCSSTransitionGroup>
```

```css
.example-enter {
  opacity: 0.01;
}

.example-enter.example-enter-active {
  opacity: 1;
  transition: opacity 500ms ease-in;
}

.example-leave {
  opacity: 1;
}

.example-leave.example-leave-active {
  opacity: 0.01;
  transition: opacity 300ms ease-in;
}
```
